// <auto-generated />
namespace siteweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class khadmi_plz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(khadmi_plz));
        
        string IMigrationMetadata.Id
        {
            get { return "201803082350238_khadmi_plz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
